-- schema_v190_geo_country_iso2.sql — бэкфилл user_proxies.geo_country → ISO2
-- Первопричина: детект писал полное имя страны, матч-сайты ждут ISO2-код.
-- Идемпотентно: трогает только строки, где geo_country длиннее 2 символов
-- (после нормализации значение = 2 символа и повторно не затрагивается).
-- Маппинг сгенерирован из services/geo_normalize.name_map() (единый источник).

UPDATE user_proxies AS p
SET geo_country = m.iso2
FROM (VALUES
  ('afghanistan','AF'),
  ('albania','AL'),
  ('algeria','DZ'),
  ('andorra','AD'),
  ('argentina','AR'),
  ('armenia','AM'),
  ('australia','AU'),
  ('austria','AT'),
  ('azerbaijan','AZ'),
  ('bangladesh','BD'),
  ('belarus','BY'),
  ('belgium','BE'),
  ('bolivia','BO'),
  ('bosnia','BA'),
  ('brazil','BR'),
  ('brunei','BN'),
  ('bulgaria','BG'),
  ('canada','CA'),
  ('chile','CL'),
  ('china','CN'),
  ('colombia','CO'),
  ('costa rica','CR'),
  ('cote d''ivoire','CI'),
  ('croatia','HR'),
  ('cuba','CU'),
  ('cyprus','CY'),
  ('czech republic','CZ'),
  ('czechia','CZ'),
  ('côte d''ivoire','CI'),
  ('democratic republic of the congo','CD'),
  ('denmark','DK'),
  ('dominican republic','DO'),
  ('dr congo','CD'),
  ('ecuador','EC'),
  ('egypt','EG'),
  ('estonia','EE'),
  ('ethiopia','ET'),
  ('finland','FI'),
  ('france','FR'),
  ('georgia','GE'),
  ('germany','DE'),
  ('ghana','GH'),
  ('great britain','GB'),
  ('greece','GR'),
  ('hong kong','HK'),
  ('hungary','HU'),
  ('iceland','IS'),
  ('india','IN'),
  ('indonesia','ID'),
  ('iran','IR'),
  ('iran, islamic republic of','IR'),
  ('iraq','IQ'),
  ('ireland','IE'),
  ('israel','IL'),
  ('italy','IT'),
  ('ivory coast','CI'),
  ('japan','JP'),
  ('jordan','JO'),
  ('kazakhstan','KZ'),
  ('kenya','KE'),
  ('korea','KR'),
  ('kosovo','XK'),
  ('laos','LA'),
  ('latvia','LV'),
  ('lebanon','LB'),
  ('liechtenstein','LI'),
  ('lithuania','LT'),
  ('luxembourg','LU'),
  ('macao','MO'),
  ('macau','MO'),
  ('malaysia','MY'),
  ('malta','MT'),
  ('mexico','MX'),
  ('moldova','MD'),
  ('monaco','MC'),
  ('montenegro','ME'),
  ('morocco','MA'),
  ('nepal','NP'),
  ('netherlands','NL'),
  ('new zealand','NZ'),
  ('nigeria','NG'),
  ('north korea','KP'),
  ('north macedonia','MK'),
  ('norway','NO'),
  ('pakistan','PK'),
  ('panama','PA'),
  ('paraguay','PY'),
  ('peru','PE'),
  ('philippines','PH'),
  ('poland','PL'),
  ('portugal','PT'),
  ('republic of korea','KR'),
  ('republic of moldova','MD'),
  ('romania','RO'),
  ('russia','RU'),
  ('russian federation','RU'),
  ('san marino','SM'),
  ('saudi arabia','SA'),
  ('serbia','RS'),
  ('singapore','SG'),
  ('slovakia','SK'),
  ('slovenia','SI'),
  ('south africa','ZA'),
  ('south korea','KR'),
  ('spain','ES'),
  ('sri lanka','LK'),
  ('sweden','SE'),
  ('switzerland','CH'),
  ('syria','SY'),
  ('syrian arab republic','SY'),
  ('taiwan','TW'),
  ('thailand','TH'),
  ('the congo','CG'),
  ('the netherlands','NL'),
  ('tunisia','TN'),
  ('turkey','TR'),
  ('turkiye','TR'),
  ('türkiye','TR'),
  ('u.s.a.','US'),
  ('uae','AE'),
  ('ukraine','UA'),
  ('united arab emirates','AE'),
  ('united kingdom','GB'),
  ('united republic of tanzania','TZ'),
  ('united states','US'),
  ('united states of america','US'),
  ('uruguay','UY'),
  ('usa','US'),
  ('uzbekistan','UZ'),
  ('venezuela','VE'),
  ('viet nam','VN'),
  ('vietnam','VN')
) AS m(name, iso2)
WHERE p.geo_country IS NOT NULL
  AND char_length(p.geo_country) > 2
  AND lower(p.geo_country) = m.name;
