module.exports = {
  apps: [
    {
      name: 'nevesty-models',
      script: 'server.js',
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 20,
      min_uptime: '10s',
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
      },
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      out_file: 'logs/app-out.log',
      error_file: 'logs/app-error.log',
    },
    {
      name: 'nevesty-scheduler',
      script: 'agents/scheduler.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 60000,
      max_memory_restart: '256M',
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
      },
      error_file: 'logs/scheduler-error.log',
      out_file: 'logs/scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'nevesty-factory',
      script: 'factory_main.py',
      interpreter: 'python3',
      cwd: '/home/user/Pablo',
      autorestart: true,
      max_restarts: 5,
      restart_delay: 30000,
      max_memory_restart: '384M',
      kill_timeout: 30000,
      env: {
        PYTHONPATH: '/home/user/Pablo',
        FACTORY_CYCLE_HOURS: '6',
      },
      error_file: '/home/user/Pablo/logs/factory-error.log',
      out_file: '/home/user/Pablo/logs/factory-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
